### ISSUE TITLE
Exercise configure.url and course.configures url should not be mandatory

### ISSUE THREAD

**Issue by Mankro** [apluslms/gitmanager#10]
If a course does not manually set any grader URL, gitmanager should use the default grader URL (`settings.DEFAULT_GRADER_URL`). A course should be able to set files for the grader in the `exercise.configure.files` field and `course.configures` list and `files` fields even if the course does not manually set any `url`. The `ConfigureOptions` class should make the `url` field optional and fill in the default when there is no value.

https://github.com/apluslms/gitmanager/blob/3d10671dcd01db794de0bd9c8d4e613ffeee7180/access/course.py#L23-L25
https://github.com/apluslms/gitmanager/blob/3d10671dcd01db794de0bd9c8d4e613ffeee7180/access/course.py#L161
https://github.com/apluslms/gitmanager/blob/3d10671dcd01db794de0bd9c8d4e613ffeee7180/access/course.py#L389

The default grader URL is already used in the backwards-compatible mode when no `configure` fields are set:
https://github.com/apluslms/gitmanager/blob/3d10671dcd01db794de0bd9c8d4e613ffeee7180/access/course.py#L215

**Comment by lainets** [comment]
I'm not a huge fan of setting the URL to the default value. What if the course wants to use some other grading service (if the goal is to have multiple, e.g. split forms from mooc-grader into a separate service)? Then they would have to specify the URL anyway in the configuration. Preferably, the course would give an alias of the grading service (e.g. "mooc-grader") that Git Manager can then translate to the correct URL. This does require a bit more work though.

Nevertheless, The easiest way to set a default value for the URL is probably to do `url: str = settings.DEFAULT_GRADER_URL`.

**Comment by Mankro** [comment]
Using aliases for the services instead of full URLs would be very good, but since we don't have it yet, the first workaround is to support courses in a backwards-compatible way and assume that they are using the default grader. I don't want to force any old course to add new configurations in the git repo just to run the course in the default grader like they have always done before.
